# Generated by Django 2.1.2 on 2018-10-13 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_pro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=8)),
                ('introduce', models.CharField(blank=True, max_length=40)),
                ('name_show', models.SmallIntegerField(default=0)),
                ('email_show', models.SmallIntegerField(default=0)),
                ('follow_show', models.SmallIntegerField(default=0)),
                ('collects_show', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
