# Generated by Django 2.1.2 on 2018-10-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20181013_1849'),
        ('users', '0003_auto_20181018_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='collects',
            field=models.ManyToManyField(blank=True, to='post.Post'),
        ),
    ]
