# Generated by Django 2.1 on 2018-08-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180819_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='excerpt',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
