# Generated by Django 2.1.2 on 2018-10-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_message_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='context',
            new_name='content',
        ),
    ]
