# Generated by Django 2.1.2 on 2018-10-19 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20181013_1849'),
        ('users', '0007_auto_20181019_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='post',
        ),
        migrations.AddField(
            model_name='message',
            name='post',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
