# Generated by Django 2.1.2 on 2018-10-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181019_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='post',
        ),
    ]
