# Generated by Django 2.1.2 on 2018-10-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_emailnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailnotification',
            old_name='User',
            new_name='user',
        ),
    ]
