# Generated by Django 2.1.2 on 2018-10-21 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20181021_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Message')),
            ],
        ),
    ]
