# Generated by Django 2.1 on 2018-08-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newscoment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='talk',
            field=models.BooleanField(default=False),
        ),
    ]
