# Generated by Django 2.1.2 on 2018-10-08 18:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_reply'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsComent',
            new_name='NewsComment',
        ),
    ]
