# Generated by Django 2.1 on 2018-08-28 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180828_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreply',
            name='reply',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='post.PostReply'),
        ),
    ]
