# Generated by Django 2.1 on 2018-08-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20180828_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreply',
            name='reply',
        ),
    ]
