# Generated by Django 2.1 on 2018-08-28 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_postreply_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreply',
            name='reply',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='post.PostReply'),
            preserve_default=False,
        ),
    ]
