# Generated by Django 2.1.2 on 2018-10-13 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20181013_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='anonym',
            new_name='anonymous',
        ),
    ]
