# Generated by Django 2.1.4 on 2019-04-09 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xnd', models.CharField(max_length=10)),
                ('xqd', models.SmallIntegerField()),
                ('number', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('faculty', models.CharField(max_length=40)),
                ('major', models.CharField(max_length=40)),
                ('a_class', models.CharField(max_length=40)),
                ('course_table', models.CharField(max_length=3000)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QueryUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=40)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_login_time', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
