# Generated by Django 2.1.4 on 2019-04-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='queryusers',
            old_name='user_id',
            new_name='user',
        ),
    ]
