# Generated by Django 2.1.4 on 2019-04-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20190409_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_table',
            field=models.TextField(),
        ),
    ]
