# Generated by Django 2.1.4 on 2019-04-28 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_auto_20190417_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryusers',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='queryusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
