# Generated by Django 2.1 on 2018-08-27 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('profession', models.CharField(blank=True, max_length=30)),
                ('facuty', models.CharField(blank=True, max_length=30)),
                ('graduate_year', models.SmallIntegerField()),
                ('work_place', models.CharField(max_length=50)),
                ('industry', models.CharField(blank=True, max_length=50)),
                ('tel_number', models.CharField(blank=True, max_length=15)),
                ('net_contact', models.CharField(blank=True, max_length=50)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
